# This file was generated by GoReleaser. DO NOT EDIT.
cask "pbuilder" do
  version "0.9.6"

  on_macos do
    on_arm do
      sha256 "fc799efc0e22ef6a2243106aa91133eab9f1507e47710842a9f7ee6c3eb34e67"
      url "https://github.com/Project-Builder-Schematics/homebrew-tap/releases/download/v#{version}/pbuilder_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cff7ef940437ebdc52a526799a705347e42f6a6e13fed2380b1bf70315974524"
      url "https://github.com/Project-Builder-Schematics/homebrew-tap/releases/download/v#{version}/pbuilder_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6a2253c2883ce2fd79d31279b95981a08bef5869ceecb0515503260a7b57c41d"
      url "https://github.com/Project-Builder-Schematics/homebrew-tap/releases/download/v#{version}/pbuilder_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "45ab9445893695d5bc45827417df87e97791e10a2ef5f536cc14b3442dbf3f3e"
      url "https://github.com/Project-Builder-Schematics/homebrew-tap/releases/download/v#{version}/pbuilder_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pbuilder"
  desc "Schematic-driven CLI for initialising, scaffolding, and maintaining software projects"
  homepage "https://github.com/Project-Builder-Schematics/homebrew-tap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "builder"

  postflight do
    if File.executable?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/builder"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    builder executes schematics through a Bun sidecar at runtime.
    Install Bun if you don't have it: https://bun.sh
      brew install oven-sh/bun/bun
  EOS
end
