# This file was generated by GoReleaser. DO NOT EDIT.
cask "pbuilder" do
  version "0.9.8"

  on_macos do
    on_arm do
      sha256 "e11d5e691bd76b98fec8bfa47bdefb279b1527741bfee1e38300e2dd7ed68927"
      url "https://github.com/Project-Builder-Schematics/homebrew-tap/releases/download/v#{version}/pbuilder_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ec709b9b6a76aa32eb7013593d46bfd306da56e65d2c524014973a3c9d6b60e0"
      url "https://github.com/Project-Builder-Schematics/homebrew-tap/releases/download/v#{version}/pbuilder_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "64a1fddd80801945770a803bc85d2088e36a83c8160a4f3b46c733d63c8142ee"
      url "https://github.com/Project-Builder-Schematics/homebrew-tap/releases/download/v#{version}/pbuilder_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b9ed4c49e581bf5c0220ef8c96eab9d6ab0ceb6c23f004b3e25d754645b90f5e"
      url "https://github.com/Project-Builder-Schematics/homebrew-tap/releases/download/v#{version}/pbuilder_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pbuilder"
  desc "Schematic-driven CLI for initialising, scaffolding, and maintaining software projects"
  homepage "https://github.com/Project-Builder-Schematics/homebrew-tap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "builder"

  postflight do
    if File.executable?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/builder"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    builder executes schematics through a Bun sidecar at runtime.
    Install Bun if you don't have it: https://bun.sh
      brew install oven-sh/bun/bun
  EOS
end
