# This file was generated by GoReleaser. DO NOT EDIT.
cask "pbuilder" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "df9869e6cbcee6f1d1ce3f2e99b87aed9858411ef57c409a8c0f06a3f10c954d"
      url "https://github.com/Project-Builder-Schematics/homebrew-tap/releases/download/v#{version}/pbuilder_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f2a95b7dfa8e3c627257df0dcf86f2d01e7882075ac623c2f58d3e0d6e12bb1"
      url "https://github.com/Project-Builder-Schematics/homebrew-tap/releases/download/v#{version}/pbuilder_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "25b6bd2e4cab88b34e77a67e427a24fb47d55a9a172064903ab11dc599e4c3e5"
      url "https://github.com/Project-Builder-Schematics/homebrew-tap/releases/download/v#{version}/pbuilder_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f27515f6e08b70e0b1062e79526d89919e633f2319c790766d59f8add8c6b18b"
      url "https://github.com/Project-Builder-Schematics/homebrew-tap/releases/download/v#{version}/pbuilder_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pbuilder"
  desc "Schematic-driven CLI for initialising, scaffolding, and maintaining software projects"
  homepage "https://github.com/Project-Builder-Schematics/homebrew-tap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "builder"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/builder"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    builder executes schematics through a Bun sidecar at runtime.
    Install Bun if you don't have it: https://bun.sh
      brew install oven-sh/bun/bun
  EOS
end
